### ISSUE TITLE
better_featured_image not exist in WP Rest API JSON feed?

### ISSUE THREAD

**Issue by rmulr** [BraadMartin/better-rest-api-featured-images#10]
Hi there,

i am trying to get featured images urls with you plugin through the WP Rest API (Version 1). After installing the plugin where to access it? There is no "better_featured_image" in any of the JSON output by WP Rest API.

thanks in advance

**Comment by BraadMartin** [comment]
Hello,

Unfortunately this plugin only supports either v2 of the REST API or the version bundled in core as of WP 4.7 I'd recommend updating to the latest version of WP if you can.
