### ISSUE TITLE
better_featured_image: null

### ISSUE THREAD

**Issue by shprink** [BraadMartin/better-rest-api-featured-images#5]
Hi Braad,

I have just updated your plugin and WP-API beta11 and I have a problem:

![image](https://cloud.githubusercontent.com/assets/1388706/12694094/c6683034-c6e6-11e5-885b-2211cb3c074a.png)

As you can see even if `featured_media=2589` => `better_featured_image: null`

Does it have to do with the fact that now the media is forbidden: http://dev.julienrenaux.fr/wp-json/wp/v2/media/2589 ?

Thanks

**Comment by BraadMartin** [comment]
Hmm, when I hit http://dev.julienrenaux.fr/wp-json/wp/v2/posts I get a response that includes the full better_featured_image field, and when I hit media/2589 I get the forbidden. The response I see on post 2585 for example looks like this:

```
"featured_media": 2589,
"better_featured_image": {
  "id": 2589,
  "alt_text": "",
  "caption": "",
  "description": "",
  "media_type": "image",
  "media_details": {
    "width": 600,
    "height": 340,
    "file": "2015/12/angular2.jpg",
    "sizes": {
      "thumbnail": {
        "file": "angular2-150x150.jpg",
        "width": 150,
        "height": 150,
        "mime-type": "image/jpeg",
        "source_url": "http://dev.julienrenaux.fr/wp-content/uploads/2015/12/angular2-150x150.jpg"
      },
      "medium": {
        "file": "angular2-300x170.jpg",
        "width": 300,
        "height": 170,
        "mime-type": "image/jpeg",
        "source_url": "http://dev.julienrenaux.fr/wp-content/uploads/2015/12/angular2-300x170.jpg"
      }
    },
    "image_meta": {
      "aperture": 0,
      "credit": "",
      "camera": "",
      "caption": "",
      "created_timestamp": 0,
      "copyright": "",
      "focal_length": 0,
      "iso": 0,
      "shutter_speed": 0,
      "title": "",
      "orientation": 0,
      "keywords": []
    }
  },
  "post": 2512,
  "source_url": "http://dev.julienrenaux.fr/wp-content/uploads/2015/12/angular2.jpg"
},
```

The Better REST API Featured Images plugin doesn't do anything to modify the response of the /media/\* endpoint. Before registering the `better_featured_image` field it does a check to confirm that the post type is set to be publicly accessible over the REST API and it checks to confirm that the post type is set to support featured images, but other than that it doesn't handle any specific restrictions.

If you can provide me with a URL that will show me a response that matches your screenshot I can investigate further. In my testing the latest version of the plugin is working great with beta 11, but if there is an issue in the plugin I definitely want to find it and fix it. Let me know if I can help further.

**Comment by shprink** [comment]
That's this one: http://dev.julienrenaux.fr/wp-json/wp/v2/posts/2587

But as you can see now it works, it is really weird, I did not touched anything over night...

I guess you can close this?!

Thanks for your time
