### ISSUE TITLE
Firsts posts loaded on my app don´t show the featured image.

### ISSUE THREAD

**Issue by pmaojo** [BraadMartin/better-rest-api-featured-images#6]
![captura de pantalla 2016-02-06 a las 18 09 08](https://cloud.githubusercontent.com/assets/411551/12868350/bec3739a-ccfc-11e5-86ca-a0b1ec3f2c20.png)

The latest posts dont retrieve the featured image, while others do... And there is a featured image on those too...

This is my code

```
        <img ng-if="post.better_featured_image" ng-src="{{post.better_featured_image.media_details.sizes.thumbnail.source_url}}" class="alignleft" />
```

**Comment by BraadMartin** [comment]
Hello pmaojo,

I'd need to see the response that the API is serving up to know whether you have the right setup there. The posts.better_featured_image... looks correct, but it would only be there if the API response was including it.

If the full field is there for the posts that are missing the image then the problem is on the Angular side. If the API response is missing the field then it's on the PHP side, and there is likely something in the error logs.

Can you paste an example of the full response for a post where the image isn't showing but the field is included in the API response? This will help me investigate the issue further.

**Comment by pmaojo** [comment]
Good one:

**post.featured_media:** 704
*_post.better_featured_image: *_{"id":704,"alt_text":"","caption":"","description":"","media_type":"image","media_details":{"width":900,"height":1365,"file":"buendis.jpg","sizes":{"thumbnail":{"file":"buendis-150x150.jpg","width":150,"height":150,"mime-type":"image/jpeg","source_url":"http://pulpomarketing.com/media/buendis-150x150.jpg"},"medium":{"file":"buendis-197x300.jpg","width":197,"height":300,"mime-type":"image/jpeg","source_url":"http://pulpomarketing.com/media/buendis-197x300.jpg"},"large":{"file":"buendis-675x1024.jpg","width":675,"height":1024,"mime-type":"image/jpeg","source_url":"http://pulpomarketing.com/media/buendis-675x1024.jpg"}},"image_meta":{"aperture":0,"credit":"","camera":"","caption":"","created_timestamp":0,"copyright":"","focal_length":0,"iso":0,"shutter_speed":0,"title":""}},"post":689,"source_url":"http://pulpomarketing.com/media/buendis.jpg"}

*_post.better_featured_image.media_details.sizes.thumbnail.source_url: *_http://pulpomarketing.com/media/buendis-150x150.jpg

Bad one:
**post.featured_media:** 
1052
**post.better_featured_image:**

*_post.better_featured_image.media_details.sizes.thumbnail.source_url: *_

...no post.better_featured_image.

**Comment by pmaojo** [comment]
thankyou!!

**Comment by BraadMartin** [comment]
Hmm, when I send a GET request to http://pulpomarketing.com/wp-json/wp/v2/posts/1040, I get:

```
  "featured_media": 1052,
  "better_featured_image": {
    "id": 1052,
    "alt_text": "",
    "caption": "",
    "description": "",
    "media_type": "image",
    "media_details": {
      "width": 843,
      "height": 541,
      "hwstring_small": "height='82' width='128'",
      "file": "cambio_algoritmo_google.png",
      "sizes": {
        "thumbnail": {
          "file": "cambio_algoritmo_google-150x150.png",
          "width": 150,
          "height": 150,
          "mime-type": "image/png",
          "source_url": "http://pulpomarketing.com/media/cambio_algoritmo_google-150x150.png"
        },
        "medium": {
          "file": "cambio_algoritmo_google-300x193.png",
          "width": 300,
          "height": 193,
          "mime-type": "image/png",
          "source_url": "http://pulpomarketing.com/media/cambio_algoritmo_google-300x193.png"
        },
        "medium_large": {
          "file": "cambio_algoritmo_google-768x493.png",
          "width": 768,
          "height": 493,
          "mime-type": "image/png",
          "source_url": "http://pulpomarketing.com/media/cambio_algoritmo_google-768x493.png"
        }
      },
      "image_meta": {
        "aperture": "0",
        "credit": "",
        "camera": "",
        "caption": "",
        "created_timestamp": "0",
        "copyright": "",
        "focal_length": "0",
        "iso": "0",
        "shutter_speed": "0",
        "title": "",
        "orientation": "0",
        "keywords": []
      }
    },
    "post": 1040,
    "source_url": "http://pulpomarketing.com/media/cambio_algoritmo_google.png"
  },
```

As you can see, the better_featured_image field is right there and has all the right data.

Can you tell me what exact request you're using? This will let me see hopefully exactly the JSON that you are seeing.

**Comment by pmaojo** [comment]
I see, yes, the json response is right. So It must be on the angular side...

I am using this app as starter: 
https://github.com/scottopolis/wpIonic

**Comment by pmaojo** [comment]
Could be something related to jpg vs png?

**Comment by pmaojo** [comment]
Thankyou for your help, and sorry, couse its my fault. The URL configured on my app had the www and removing it magically makes my thumbnails show. So, your plugin has nothing to do with my problem 

:+1:
